[package]
name = "agentpay"
version = "0.1.0"
description = "AgentPay escrow and settlement program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "agentpay"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "1.2.0"
anchor-spl = { version = "1.2.0", features = ["token_2022"] }
solana-instructions-sysvar = "3.0.1"
solana-sdk-ids = "3.1.0"
solana-sha256-hasher = "3.1.0"
